[project]
name = "nota-web-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"


dependencies = [
    "alembic>=1.17.0",
    "asyncpg>=0.30.0",
    "bcrypt>=5.0.0",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.125.0",
    "fpdf2>=2.8.5",
    "loguru>=0.7.3",
    "psycopg2-binary>=2.9.11",
    "pydantic-settings>=2.11.0",
    "pyjwt[crypto]>=2.10.1",
    "sqlalchemy[asyncio]>=2.0.44",
    "testcontainers[postgres]>=4.13.3",
    "types-fpdf2>=2.8.4.20251031",
]

[dependency-groups]

lint = [
    "pre-commit>=4.5.0",
    "mypy>=1.18.2",
    "ruff>=0.14.1",
    "rust-just>=1.43.0",
]

test = [
    "httpx>=0.28.1",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
]

[tool.mypy]
plugins = ['pydantic.mypy']

[[tool.mypy.overrides]]
module = "testcontainers.*"
ignore_missing_imports = true

[tool.ruff.lint]
select = ["I", "E", "W", "F", "C","N"]

[tool.pytest.ini_options]
pythonpath = ". src"
testpaths = ["tests"]
