"""empty message

Revision ID: 9eb122cbf300
Revises: 6266bed0561d
Create Date: 2025-10-25 19:38:14.709242

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9eb122cbf300'
down_revision: Union[str, Sequence[str], None] = '6266bed0561d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
