"""add commision for services

Revision ID: c00d3da268f4
Revises: 9940d73f74cc
Create Date: 2026-01-03 13:00:09.233980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00d3da268f4'
down_revision: Union[str, Sequence[str], None] = '9940d73f74cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('bookings', sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('bookings', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'total_amount')
    op.drop_column('bookings', 'commission_amount')
    op.drop_column('bookings', 'commission_percent')
    # ### end Alembic commands ###
