"""empty message

Revision ID: f38f05288773
Revises: 686357a167e3
Create Date: 2025-12-06 16:08:55.579212

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f38f05288773'
down_revision: Union[str, Sequence[str], None] = '686357a167e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'] ),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_customer_profiles_id'), 'customer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_customer_profiles_phone_number'), 'customer_profiles', ['phone_number'], unique=True)
    op.create_index(op.f('ix_customer_profiles_user_id'), 'customer_profiles', ['user_id'], unique=True)
    op.create_table('notary_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('license_number', sa.String(length=256), nullable=False),
    sa.Column('inn', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'] ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('inn'),
    sa.UniqueConstraint('license_number'),
    )
    op.create_index(op.f('ix_notary_profiles_id'), 'notary_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_notary_profiles_phone_number'), 'notary_profiles', ['phone_number'], unique=True)
    op.create_index(op.f('ix_notary_profiles_user_id'), 'notary_profiles', ['user_id'], unique=True)
    op.alter_column('services', 'title',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.alter_column('services', 'title',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_index(op.f('ix_notary_profiles_user_id'), table_name='notary_profiles')
    op.drop_index(op.f('ix_notary_profiles_phone_number'), table_name='notary_profiles')
    op.drop_index(op.f('ix_notary_profiles_id'), table_name='notary_profiles')
    op.drop_table('notary_profiles')
    op.drop_index(op.f('ix_customer_profiles_user_id'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_phone_number'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_id'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    # ### end Alembic commands ###
